name: video_behavior_tracking
channels:
- conda-forge
- defaults
- menpo
dependencies:
- "python >= 3.6"
- numpy
- scipy
- pandas
- opencv
- tqdm
- setuptools
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- jupyterlab
- nb_conda
